wordsList1= [
 "pager","nuées","vitra", "solde", "lyric", "group", "motif", "ladin", "subît",
 "barge", "fixés", "ponts", "tanne", "fonda", "sitar", "gonder", "fusât",
 "bière","à","chaud","heure","couleur","guerre","gagner","autre","chemin","descendre",
 "exemple","acheter","avancer","argent","chambre","haut","action","avant","chercher",
 "devant","faim"]
wordsList = {
    "pager" : "Synonyme d'un BIP du téléphone!",
    "nuées" : "Nuage de grande étendue, généralement épais et sombre, annonciateur de pluie ou d'orage",
    "vitra" : "Verbe qui veut dire Garnir de vitres",
    "solde" : "Synonyme de bilan. Différence entre le débit et le crédit!",
    "lyric" : "Texte chanté!",
    "group" : "Sac cacheté servant à l'expédition d'argent ou de valeurs",
    "motif" : "Élément d'ordre (généralement) mental qui incite à agir ou, selon le cas, à réagir (en fournissant, le cas échéant et à posteriori, une justification de l'action ou de la réaction)",
    "ladin" : "Groupe de langues romanes parlées dans certaines régions de la Suisse, de l'Autriche et de l'Italie.",
    "subît" : "Être soumis à un phénomène physique, une condition naturelle ou Être soumis à un état, une action, une situation",
    "barge" : "Oiseau Limicole du genre Limosa!",
    "fixés" : "Nom(en pluriel) dérivant du verbe qui veut dire : Agir sur un être ou sur une chose en vue de leur donner une assise, de les établir et de les maintenir à une place ou dans une position donnée.",
    "ponts" : "Ouvrage généralement en pierre, en bois ou en métal permettant de franchir une dépression ou un obstacle (voie de communication, cours d'eau, en particulier) en reliant les deux bords de la dépression ou en enjambant l'obstacle",
    "tanne" : "Marque brune restant sur une peau d'animal après tannage.",
    "fonda" : "le conjugué au passé du verbe signifiant Poser les fondements (d'une construction)",
    "sitar" : "Instrument à cordes pincées, aux harmoniques très riches, fait d'une caisse de résonance hémisphérique et d'un long manche sur lequel sont fixées des touches mobiles.",
    "gonder" : "Mettre des gonds à une porte",
    "fusât" : "le conjugué à l'imparfait du verbe signifiant Jaillir, Sortir Brusquement, Se repandre etc..",
    "bière" : "Boisson alcoolisée obtenue par la fermentation d'un moût fabriqué avec du houblon ",
    "à" : "Préposition qui introduit un complément circonstanciel de lieu." ,
    "chaud" : "Témperature plus haute que la normale!" ,
    "heure" : "Unité de mésure du temps" ,
    "couleur" : "Du latin Color, ce qui n'est pas blanc ni noir!" ,
    "guerre" : "Conflit entre deux nations!",
    "gagner" : "Acquérir par son travail ou par son initiative!, Être le vainqueur!" ,
    "autre" : "Du latin alter, signifie celui qui n'est pas moi!" ,
    "chemin" : "Voie pour aller d'un lieu à un autre!" ,
    "descendre" : "Verbe qui signifie Aller du Haut en bas!" ,
    "exemple" : "Ce qui peut servir de modèle! Ce qui peut être imité!" ,
    "acheter" : "Verbe qui veut dire Acquérir quelques choses en l'échangeant contre sa valeur en devise!" ,
    "avancer" : "Verbe signifiant Pousser en Avant; porter en avant!" ,
    "argent" : "Métal Solide de numéro atomique 47 et de symbole Ag!" ,
    "chambre" :"Toute pièce habitable d'une maison et principalement là où on dort!" ,
    "haut" : "Qui est élevé! Par opposition à qui est pétit!" ,
    "action" : "Opération par laquelle se produit un effet; Tout ce qu'on fait",
    "avant" : "Préposition qui marque la priorité ou l'antériorité de temps!" ,
    "chercher" : "Verbe signifiant se donner en mouvement, du soin ou de la peine pour trouver quelqu'un ou quelques choses!" ,
    "devant" : "Préposition qui signifie en avant de !" ,
    "faim": "Sensation qui rélève l'envie ou le besoin de manger!"
}

additionnalArray = [
"pians", "drame", "houri", "cabot", "films", "créât", "bramé", "havie",
"errai", "listé", "virez", "lérot", "bleue", "ormes", "mates", "makis", "saros",
"miter", "sotte", "voles", "fille", "sténo", "fange", "pesez", "coxal", "jeeps",
"aises", "taras", "brûlé", "gîtât", "folié", "évase", "pacha", "disco", "lovas",
"vanna", "tuais", "joncé", "choir", "orles", "bacul", "kicks", "hôtes", "maser",
"close", "gérez", "rondi", "geins", "pêche", "mamie", "adula", "tempo", "bêlas",
"haler", "oisif", "turbe", "rêvez", "polît", "monde", "carda", "lifta", "biffé",
"périr", "radis", "genou", "épiça", "imbue", "jacée", "sciés", "fugué", "oeuvé",
"élite", "doses", "butes", "jerez", "goton", "vinez", "bigle", "purée", "tomât",
"ébahi", "borné", "amusé", "huila", "vagit", "poilé", "pifés", "quels", "gâtât",
"humez", "rimez", "glèbe", "damée", "jeudi", "jouai", "lista", "bénit", "tomai",
"relit", "biefs", "aérés", "coing", "jappé", "monté", "lotes", "roque", "grêla",
"obéie", "ornez", "paver", "bagua", "mutez", "aidât", "licol", "porcs", "roula",
"schah", "viocs", "rotez", "tenue", "hélas", "boude", "oncle", "lapée", "belle",
 "tétas", "furia", "major", "palpé", "brase", "huais"

]
additionnalDic = {
"pians" : "",
"drame" : "",
"houri" : "",
"cabot" : "",
"films" : "",
"créât" : "",
"bramé" : "",
"havie" : "",
"errai" : "",
"listé" : "",
"virez" : "",
"lérot" : "",
"bleue" : "",
"ormes" : "",
"mates" : "",
"makis" : "",
"saros" : "",
"miter" : "",
"sotte" : "",
"voles" : "",
"fille" : "",
"sténo" : "",
"fange" : "",
"pesez" : "",
"coxal" : "",
"jeeps" : "",
"aises" : "",
"taras" : "",
"brûlé" : "",
"gîtât" : "",
"folié" : "",
"évase" : "",
"pacha" : "",
"disco" : "",
"lovas" : "",
"vanna" : "",
"tuais" : "",
"joncé" : "",
"choir" : "",
"orles" : "",
"bacul" : "",
"kicks" : "",
"hôtes" : "",
"maser" : "",
"close" : "",
"gérez" : "",
"rondi" : "",
"geins" : "",
"pêche" : "",
"mamie" : "",
"adula" : "",
"tempo" : "",
"bêlas" : "",
"haler" : "",
"oisif" : "",
"turbe" : "",
"rêvez" : "",
"polît" : "",
"monde" : "",
"carda" : "",
"lifta" : "",
"biffé" : "",
"périr" : "",
"radis" : "",
"genou" : "",
"épiça" : "",
"imbue" : "",
"jacée" : "",
"sciés" : "",
"fugué" : "",
}
